### ISSUE TITLE
[NEW FEATURE] C++ implementation?

### ISSUE THREAD

**Issue by davidefer** [Luos-io/Luos#106]
Hi 
I find the project cool.
Do you plan to port it to C++? It would fit very well with your framework.
Thanks in advance

**Comment by nicolas-rabault** [comment]
Hi @davidefer,
No we don't plan to port it to C++ because people making C++ can make C but not the other way. So C is more universal.
Yes Luos could be really good in C++ and a lot of our API are object-oriented.
We are using it on C++ code on Arduino if you need to.
Also If you want you could make a binding API to use Luos in C++ code ;)
