### ISSUE TITLE
[BUG] Missing submodules

### ISSUE THREAD

**Issue by sfermigier** [Luos-io/Luos#72]
In the readme: *This repository contains a submodule. The examples folder is linked to another repository. That means this folder won't be cloned with a regular git clone.*

This didn't seem to be the case.

Running `git clone --recursive https://github.com/Luos-io/Luos.git` doesn't make an `examples` directory appear.

**Comment by nicolas-rabault** [comment]
Good catch @sfermigier,

Indeed this is something we don't checked from a long time, and I think nobody tried to use it since we make it.

The example folder in the Luos lib is an interesting thing if it is directly usable by IDE (such as platformio) in an examples list menu or something. But our Example repo is more and more complexe and deal with more and more architecture making it complexe to be compatible with this kind of IDE graphical feature.

I think we could remove this submodule.

@sfermigier, do you have any insight about it?

**Comment by sfermigier** [comment]
"do you have any insight about it?" -> Nope, just trying to figure out the organisation of your repositories.

**Comment by nicolas-rabault** [comment]
ok, so I will remove it.
